### ISSUE TITLE
`mask_file` should have keys the names in `mask_names`

### ISSUE THREAD

**Issue by carlosggarcia** [LSSTDESC/TJPCov#118]
At the moment `mask_file` has as keys the tracer names and as value, the path or associated map. I think it would be clearer and better to have as key the name assigned in `mask_names`. 

E.g. imagine that we have 3 galaxy clustering bins sharing the same mask. At the moment one need to specify:
```
  mask_file:
    gc__0: ./tests/benchmarks/32_DES_tjpcov_bm/catalogs/mask_DESgc__0.fits.gz
    gc__1: ./tests/benchmarks/32_DES_tjpcov_bm/catalogs/mask_DESgc__0.fits.gz
    gc__2: ./tests/benchmarks/32_DES_tjpcov_bm/catalogs/mask_DESgc__0.fits.gz

  mask_names:
    gc__0: mask_gc
    gc__1: mask_gc
    gc__2: mask_gc
```

However, it would probably be clearer and cleaner to say
```
  mask_file:
    mask_gc: ./tests/benchmarks/32_DES_tjpcov_bm/catalogs/mask_DESgc__0.fits.gz

  mask_names:
    gc__0: mask_gc
    gc__1: mask_gc
    gc__2: mask_gc
```
